[build]
  command = "npm run build"
  publish = "out"

[[plugins]]
  # Disable the Next.js SSR plugin — this site is a static export
  # package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
